services:
  nginx:
    image: nginx
    volumes:
      - ./public_html:/usr/share/nginx/html:ro
    ports:
      - 80:80
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    restart: unless-stopped
